// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
var whoami_default = defineTool({
  name: "whoami",
  title: "Quem sou eu",
  description: "Retorna o id e o email do usu\xE1rio autenticado no app. \xDAtil para verificar a conex\xE3o.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const info = { user_id: ctx.getUserId(), email: ctx.getUserEmail(), client_id: ctx.getClientId() };
    return {
      content: [{ type: "text", text: JSON.stringify(info) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/list-produtos.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_produtos_default = defineTool2({
  name: "list_produtos",
  title: "Listar produtos",
  description: "Lista/pesquisa produtos cadastrados da loja pelo nome (descri\xE7\xE3o), c\xF3digo interno ou EAN. Retorna at\xE9 50 produtos com id, c\xF3digo, EAN, descri\xE7\xE3o, categoria, pre\xE7o regular.",
  inputSchema: {
    search: z.string().optional().describe("Texto para buscar em descri\xE7\xE3o, c\xF3digo interno ou EAN. Opcional."),
    limit: z.number().int().min(1).max(50).optional().describe("M\xE1ximo de resultados (default 20, teto 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const sb = supabaseForUser(ctx);
    let q = sb.from("produtos").select("id, codigo_interno, ean, descricao, categoria, preco_regular").limit(limit ?? 20);
    if (search && search.trim()) {
      const s = search.trim();
      q = q.or(`descricao.ilike.%${s}%,codigo_interno.ilike.%${s}%,ean.ilike.%${s}%`);
    }
    const { data, error } = await q;
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { produtos: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-encartes.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_encartes_default = defineTool3({
  name: "list_encartes",
  title: "Listar encartes",
  description: "Lista os encartes (flyers) do usu\xE1rio autenticado, com nome, tema, formato, validade e data de cria\xE7\xE3o.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).optional().describe("M\xE1ximo de resultados (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const sb = supabaseForUser2(ctx);
    const { data, error } = await sb.from("encartes").select("*").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { encartes: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-vendas-padaria.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_vendas_padaria_default = defineTool4({
  name: "list_vendas_padaria",
  title: "Listar vendas da padaria",
  description: "Consulta linhas da tabela de vendas da padaria, filtrando opcionalmente por ano, m\xEAs e loja. Retorna at\xE9 100 registros com data, loja, vendas/meta, margem/meta, volume, lucro e part_percent.",
  inputSchema: {
    ano: z3.number().int().min(2e3).max(2100).optional().describe("Filtrar pelo ano (ex: 2026)."),
    mes: z3.number().int().min(1).max(12).optional().describe("Filtrar pelo m\xEAs (1-12)."),
    loja: z3.string().optional().describe("Filtrar pela loja (match exato)."),
    limit: z3.number().int().min(1).max(100).optional().describe("M\xE1ximo de resultados (default 31).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ ano, mes, loja, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const sb = supabaseForUser3(ctx);
    let q = sb.from("vendas_padaria").select("*").order("data", { ascending: true }).limit(limit ?? 31);
    if (ano !== void 0) q = q.eq("ano", ano);
    if (mes !== void 0) q = q.eq("mes", mes);
    if (loja) q = q.eq("loja", loja);
    const { data, error } = await q;
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { vendas: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "pfflraftymstgtslofno";
var mcp_default = defineMcp({
  name: "andrade-consultoria-mcp",
  title: "Andrade Consultoria MCP",
  version: "0.1.0",
  instructions: "Ferramentas para o painel comercial da Andrade Consultoria. Use `whoami` para verificar a conex\xE3o, `list_produtos` para consultar o cadastro de produtos, `list_encartes` para listar encartes salvos do usu\xE1rio e `list_vendas_padaria` para consultar as vendas di\xE1rias da padaria (filtre por ano, m\xEAs ou loja). Todas as consultas respeitam as permiss\xF5es do usu\xE1rio autenticado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_produtos_default, list_encartes_default, list_vendas_padaria_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
